### ISSUE TITLE
github redirects to port 8000, not 3000

### ISSUE THREAD

**Issue by jtauber** [pinax/patch-game#13]
I guess that means it's not honouring the site domain?

**Comment by paltman** [comment]
github isn't doing this.  it's buried in the bowels of python-social-auth.  I don't think it's worth fixing as it's just local dev and it will still work on 8000 and it's not hard to just change to 3000.

**Comment by paltman** [comment]
it's inspecting the request itself which _is_ on port 8000.  We'd have to monkey path social auth or something.
